# nodejs-container-app.yml

jobs:
- job: BuildNodeJsContainerApp
  displayName: Build Node.js Container Image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      containerRegistry: 'ServiceConnection'
      repository:  'https://github.com/ResmiADevi/package.json.git'
      command: 'build'
      Dockerfile: 'Dockerfile'
      buildContext: .
      tags: |
        $(Build.BuildId)
  - task: Docker@2
    displayName: Push Docker Image
    inputs:
      containerRegistry: 'ServiceConnection'
      repository: 'https://github.com/ResmiADevi/package.json.git'
      command: 'push'
      tags: |
        $(Build.BuildId)
        
